version: '2'
services:
    petstore-app:
        image: petstore
        external_links:
            - petstore-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/PetStore
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    petstore-postgresql:
        extends:
            file: postgresql.yml
            service: petstore-postgresql
